language: node_js
node_js:
    - lts/*
script:
    - npm run docs:build
    - npm run cname
deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs/.vuepress/dist
    github_token: $ahriknow
    keep-history: true
    on:
        branch: master
